### PR TITLE
add missing `catch`es [so it builds]

### PR DESCRIPTION
**Pull request by JeffreySarnoff**
two try blocks were missing catch
test/REQUiRE had HttpParser, I replaced that with URIParser

### CODE REVIEW

**Comment by staticfloat** [comment]
Why did you change it to URIParser? It looks to me like it should still be HTTPParser.

**Comment by JeffreySarnoff** [comment]
(a) I thought URIParser exported the more up-to-date version of the `URI(..)` function
(b) |t seemed that the only use of HttpParser was for `URI`
(c) HttpParser does not build and was blocking this from working
Of those, (c) was true last night and (a), (b) were based on a cursory look by unfamiliar eyes
It makes no difference to me -- just need BinDeps to work so people who want to do so can use ArbNumerics after my talk.  Please make any changes that help -- I'm about to fly.

**Comment by staticfloat** [comment]
Okay then, you will need to change the `using` within the `test/runtests.jl` file as well.

**Comment by tkelman** [comment]
URIParser doesn't use BinDeps, HttpParser does. It's a test-only dependency and should be left alone.

**Comment by JeffreySarnoff** [comment]
yes! it works with nightly

**Pull request closed without merging**
